apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: votingappcontainerregistry.azurecr.io/workerapp:30
        name: worker
      imagePullSecret:
      - name: acr-secret